services:
  bot:
    build: .
    container_name: concisely-bot
    env_file:
      - .env
    environment:
      - WIDE_LOG_DIR=/app/logs
      - DB_PATH=/data
    volumes:
      - ./src-ts:/app/src-ts
      - ./logs:/app/logs
      - ./data:/data
    restart: unless-stopped
